### ISSUE TITLE
is there a way to set priority?

### ISSUE THREAD

**Issue by gaboesquivel** [EngineeringMode/Grapnel.js#22]
I would like to set priority for conflicting routes like these
```javascript
    router.get('/doSomethingElse', doSomethingElse);
    
    //displays the JST that matches the pagename in the url
    router.get('/:page?', function (req) {
      var p = req.params.page || 'homepage';
      document.getElementByID('main').innerHTML = JST[p](getData(p));
    });
```

problem is doSomethingElse is never called.  so I have to check params inside my other route.
It would be nice to be able specify route priority.

**Comment by EngineeringMode** [comment]
The route priority is based on when the route is created. For example, if you had `router.get('/doSomethingElse', doSomethingElse)` route after your `router.get('/:page?', handler)` route, it will have a lower priority.
