### ISSUE TITLE
Calling router.get() on the same route more than once

### ISSUE THREAD

**Issue by PanzerKunst** [EngineeringMode/Grapnel.js#26]
Hi,

I noticed that calling `router.get` twice on the same route made that the callback function is executed twice once that route is accessed. What would be ideal, is that when calling `get` on an route already defined in the router, it would replace the existing callback by the new one.

If that is not possible, as an alternative, is there a way to check if a route is already defined in the router, in order then to avoid re-executing `get` on that route?

**Comment by PanzerKunst** [comment]
Hi EngineeringMode.

What do you think of this issue?

**Comment by EngineeringMode** [comment]
@PanzerKunst Traditional functionality of a router suggests that when a callback is assigned to a route, that callback must be called when the router matches the route(s). So if multiple callbacks are defined on the same route, all of those callbacks must be ran. However, you can prevent any unwanted callbacks from being called by using `event.stopPropagation()`.

**Comment by PanzerKunst** [comment]
Thanks for your answer.

I see several ways to solve my problem then:
- Preventing unwanted callbacks from being called. Precisely, this means in my case preventing all callbacks to a route but the latest which has been added.
- Removing callbacks to a route
- Checking if a callback exists for a route, in which case I then would skip any additional `get` calls for that route.

Can you give me more details on how to achieve one (or more) of those cases?

**Comment by EngineeringMode** [comment]
Why wouldn't you just only define the route once?

**Comment by PanzerKunst** [comment]
I'm having trouble doing just that. I'm building a component-based single page webapp. Each component, when it initialized, adds its routes to the router (one router, global to the app). It turns out that some components may be initialized more than once. I don't manage to clean the component's routes before a re-init. Do you have a suggestion on how I should proceed? Maybe a different design?
