### ISSUE TITLE
Follow semver

### ISSUE THREAD

**Issue by Nicolab** [EngineeringMode/Grapnel.js#27]
Hello,

since the release v0.5.2 to the release v0.5.6, there were new features and break in the API.

If I upgrade v0.5.2 to v0.5.6, my app doesn't work. It's not important, I'll find why.

Some changes may cause a break :
  * require('grapnel').Grapnel now is undefined with Webpack and browserify
  * anchor, hash and Grapnel().router are removed

These changes are logical, Grapnel evolves well :) 
But are not simple patch or bug fix. (It's minor or major changes).

Please can you follow the [semver](http://semver.org) for allowing the peace of mind when we added a rule in package.json, like `"grapnel": "^0.5.0"` 

Thanks for your work!

(sorry for my bad english)

**Comment by EngineeringMode** [comment]
@nicolab Grapnel has always used semantic versioning, I've just never had a major release because it still needs testing (beta). The last version `v0.5.6` had two breakers in the release but there were deprecation warnings in there for over a year. It was time.


Hope this helps. :]

**Comment by Nicolab** [comment]
Thanks for your reply.
I have read the changes in releases, it's very convenient to be able to see everything.
My suggestion is just to properly configure dependencies in the package.json. Example if there is a break, then up to the next minor `0.6.0  (instead a patch).

It's just a suggestion to simplify the dependencies management :)
