### ISSUE TITLE
Hashchange handling not working with Browserify

### ISSUE THREAD

**Issue by davidnorth** [EngineeringMode/Grapnel.js#29]
It seems to be assuming that root === window which isnt the case with browserify. So eventName ends up being 'navigate' instead of hashchange. 
If I stick 'root = window' at the top of the iife it does work.
Maybe it'd be a good idea to check typeof window === 'undefined' and assign that to root.

**Comment by davidnorth** [comment]
This is what I did to fix: https://github.com/davidnorth/Grapnel.js/blob/master/src/grapnel.js#L14

**Comment by EngineeringMode** [comment]
@davidnorth Grapnel does not assume root === window, but creating an instance in Browserify will not apply event listeners to event.navigate by default in an upcoming release.

**Comment by EngineeringMode** [comment]
Landed in `0.5.7`

**Comment by davidnorth** [comment]
Many thanks
