### ISSUE TITLE
preventDefault

### ISSUE THREAD

**Issue by daslicht** [EngineeringMode/Grapnel.js#46]
Even tho I have the following code, the page will still reload:
``` 
router.get('/about', function(req, event) {
		event.preventDefault(); 
...
```
What am I missing please?

**Comment by EngineeringMode** [comment]
Hi @daslicht, when you're setting a route, you're setting an event listener. So your handler in this case *is* the event handler. So in your case, it's too late to call `preventDefault` on an event that's already been fired.

```javascript
router.get('/about', function(req, event){
    event.callbackRan // true
});
```

You can prevent route handlers from being fired by listening for route change events:
```javascript
router.on('match', function(event){
    if(event.route === '/about'){
        event.preventDefault();
    }
});
```
